Fix
Change-Id: Icd6ddc94981b4621e05a91c50d2c0b50dd9e249b

diff --git a/tools/xen/mocks b/tools/xen/mocks
--- a/tools/xen/mocks
+++ b/tools/xen/mocks
@@ -34,6 +34,9 @@ function mktemp {
 }
 
 function wget {
+    if echo "$@" | grep -q please_fail; then
+        exit 1
+    fi
     echo "wget $@" >> $LIST_OF_ACTIONS
 }
 
